version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: vrum_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/vrum_db
    depends_on:
      - postgres
    volumes:
      - .:/app

volumes:
  postgres_data:
